from __future__ import annotations

from .mapper import QmlNode


IMPORTS = """import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
"""


def emit_qml(root: QmlNode) -> str:
    body = _emit_node(root, level=1)
    return (
        f"{IMPORTS}\n"
        "ApplicationWindow {\n"
        "    visible: true\n"
        "    width: 1000\n"
        "    height: 700\n"
        "    title: \"Generated by html-for-plasma\"\n"
        f"{body}\n"
        "}\n"
    )


def _emit_node(node: QmlNode, level: int) -> str:
    indent = "    " * level
    lines = [f"{indent}{node.component} {{"]

    for key, value in node.props.items():
        lines.append(f"{indent}    {key}: {value}")

    for child in node.children:
        lines.append(_emit_node(child, level + 1))

    lines.append(f"{indent}}}")
    return "\n".join(lines)
